baseURL = 'https://ehsanaramide.github.io/'
languageCode = 'en-us'
title = 'Ehsan Aramide'
theme = 'xmin'
footnotereturnlinkcontents = "↩"

[permalinks]
note = "/note/:year/:month/:day/:slug/"

[menu]
[[menu.main]]
name = "Home"
url = ""
weight = 1

[[menu.main]]
name = "About"
url = "about/"
weight = 2

[[menu.main]]
name = "Notes"
url = "note/"
weight = 3

[[menu.main]]
name = "Subscribe"
url = "index.xml"
weight = 4


[params]
description = "Personal Site of Ehsan Aramide. If you want to contribute, take a look at https://github.com/EhsanAramide/ehsanaramide.github.io"
footer = "&copy; [Ehsan Aramide](https://ehsanaramide.github.io) 2024 -- {Year} | [Github](https://github.com/EhsanAramide) | [LinkedIn](https://www.linkedin.com/in/ehsanaramide)"

[markup]
[markup.highlight]
style = "friendly"
[markup.goldmark.renderer]
unsafe = true